import React, { useState } from 'react';
import { formatDateForAdditionalField, getDateFormatString, parseDateForAdditionalField } from '../additionalFielsUtil';
import MrcDatePickerInput from '../../DatePicker';
import { DefaultFieldPropTypes } from '../AdditionalFieldsPropTypes';
import CalendarIcon from '../../icons/calendar.svg';

/**
 * FieldDate gets an string formatted based on format generated by parseDateForAdditionalField and sends to inner
 * datepicker a date. When inner datepicker changes the value, on state will be saved a string formatted by
 * formatDateForAdditionalField. This two functions should be always in sync.
 */
export function FieldDate(props) {
    const [value, setValue] = useState(props.elem.value);
    const dateFormat = getDateFormatString();
    const onChangeDate = value => {
        const val = formatDateForAdditionalField(value);
        if (val !== props.elem.value) {
            setValue(val);
            props.onChange(val);
            props.onBlur();
        }
    };

    return (
        <div>
            <MrcDatePickerInput
                className="m-input-element"
                {...props}
                selected={parseDateForAdditionalField(value)}
                onChange={onChangeDate}
                // minDate={new Date(new Date().getTime() + 86400000)} // + 1 day in ms
                showYearDropdown={true}
                dateFormat={dateFormat}
                placeholderText={dateFormat}
                id={'datepicker-' + props.elem.id}
            />
            <img
                htmlFor={'datepicker-' + props.elem.id}
                className="mrc-icon-small date-picker-icon"
                src={CalendarIcon}
            />
        </div>
    );
}

FieldDate.propTypes = { ...DefaultFieldPropTypes };
