import React from 'react';
import { storiesOf } from '@storybook/react';
import CustomerDataGroup from '../CustomerDataGroup';

storiesOf('Service Components/CustomerDataGroup', module).add('customers data in group', () => (
    <CustomerDataGroup
        customers={[
            {
                country: 'DE',
                zipCode: '40227',
                lastName: 'Anylastname',
                storeNumber: '10',
                paymentAllowanceCd: '3',
                legalFormDescription: 'Test Description',
                companyFoundationDate: '2015-10-09T00:00:00+02:00',
                city: 'Düsseldorf',
                houseNumber: '2',
                creditLimitStatus: 'valid',
                vatEuNumber: null,
                creditSettlePeriodCd: '3',
                street: 'Heppenheimer Weg',
                segment: 'SCO',
                badDebits: '1',
                birthDay: '1971-10-09T00:00:00+02:00',
                registrationDate: '2011-10-09T00:00:00+02:00',
                creditLimit: 123.4,
                customerLastName: 'Anylastname',
                companyOwnerFirstName: 'First',
                companyOwnerLastName: 'Last',
                vatSpecNumber: '123/78234/8901',
                email: 'someone@example.com',
                mobilePhoneNumber: '+49 160 98765432',
                blockingReason: '2',
                checkoutCheckCode: 30,
                branchId: '110',
                branchDescription: 'Test Branch',
                limitExhaustion: 123,
                salesLine: null,
                customerNumber: '555',
                legalForm: 'LLC',
                storeAndCustomerNumber: null,
                typeCode: 'NORM',
                firstName: 'Anyfirstname',
                creditSettleTypeCd: '1',
                phoneNumber: '+49 123 4567',
                customerFirstName: 'Anyfirstname',
                creditSettleFrequencyCd: '',
                currentPayment: {
                    creditProduct: 'mrc.payment.METRO_Cash',
                    creditPeriod: 'mrc.payment.3',
                    debitType: 'mrc.payment.Firmenlastschriftmandat',
                    backend: {
                        paymentAllowanceCd: 3,
                        creditSettleTypeCd: 1,
                        creditSettlePeriodCd: 3,
                        creditSettleFrequencyCd: null,
                        stringRepresentation: '3_1_3_null',
                    },
                },
            },
            {
                country: 'DE',
                zipCode: '40227',
                lastName: '',
                storeNumber: '10',
                paymentAllowanceCd: '3',
                city: 'Düsseldorf',
                houseNumber: '2',
                creditLimitStatus: 'valid',
                vatEuNumber: '1117',
                creditSettlePeriodCd: '3',
                street: 'Heppenheimer Weg',
                badDebits: '1',
                registrationDate: '2011-10-09T00:00:00+02:00',
                creditLimit: 1711.4,
                customerLastName: 'Test2',
                vatSpecNumber: null,
                email: '',
                mobilePhoneNumber: '',
                branchId: '1',
                limitExhaustion: 123,
                salesLine: null,
                customerNumber: '88',
                legalForm: 'LLC',
                storeAndCustomerNumber: null,
                typeCode: 'NORM',
                firstName: '',
                creditSettleTypeCd: '1',
                phoneNumber: '+49 123 4567',
                customerFirstName: '',
                creditSettleFrequencyCd: '',
                blockingReason: null,
                checkoutCheckCode: null,
                currentPayment: {
                    creditProduct: 'mrc.payment.METRO_Cash',
                    creditPeriod: 'mrc.payment.3',
                    debitType: 'mrc.payment.Firmenlastschriftmandat',
                    backend: {
                        paymentAllowanceCd: 3,
                        creditSettleTypeCd: 1,
                        creditSettlePeriodCd: 3,
                        creditSettleFrequencyCd: null,
                        stringRepresentation: '3_1_3_null',
                    },
                },
            },
        ]}
        countriesWithDifferentBlockingCodes={['ES']}
    />
));
