import React, { useState } from 'react';
import { storiesOf } from '@storybook/react';
import '../Util/imports';

import HistoryDetails from '../History/HistoryDetails';
import CustomerSummary from '../History/CustomerSummary';

let historyCustomerData = {
    limitRequests: {
        '-1234': {
            id: '-1234',
            creationTimestamp: '2020-05-08T13:32:19Z',
            attachments: [
                {
                    id: 'ebbc89ad-c59d-4860-a9b4-bc0d5802f43a',
                    contentUri: 'http://google.ro',
                    title: 'This is a csv file',
                    size: 1233,
                    contentType: 'text/csv',
                    filename: 'filename_csv.csv',
                    fileType: 'fileType',
                    uploadTimestamp: '2017-12-12T08:10:19Z',
                    uploaderPosition: 'HO',
                    uploaderPrincipalName: 'dan-catalin.delea@metrosystems.ro',
                    expiryDate: null,
                    amount: null,
                    metadataJson: null,
                    markedForDeletion: false,
                },
                {
                    id: '6d6d26b3-3346-4da3-8440-b98d728c513f',
                    contentUri: 'http://google.ro',
                    title: 'This is a pdf file',
                    size: 1233,
                    contentType: 'application/pdf',
                    filename: 'filename_pdf.pdf',
                    fileType: 'contract',
                    uploadTimestamp: '2020-05-08T13:32:19Z',
                    uploaderPosition: 'CC',
                    uploaderPrincipalName: 'alexandru.dita@metrosystems.ro',
                    expiryDate: '2020-05-18T13:32:19Z',
                    amount: 100,
                    metadataJson:
                        '{"country":"DE","type":"contract","label":"mrc.attachments.types.contract","remark":"Digital version to improve efficiency","fields":[{"field_label":"mrc.attachments.fields.contract.start_date","data_type":"Date","mandatory":true,"validation_operation":"LESS_THAN_AND_EQUALS","validation_argument":"TODAY","value":1580940000000},{"field_label":"mrc.attachments.fields.contract.expiration_date","data_type":"Date","mandatory":true,"field_in_db":"expiry_date","validation_operation":"GREATER_THAN_AND_EQUALS","validation_argument":"TODAY","value":1581026400000}]}',
                    markedForDeletion: false,
                },
            ],
            comments: [
                {
                    id: '1',
                    comment: 'This is the second comment',
                    uploadTimestamp: '2020-05-08T13:32:19Z',
                    uploaderPosition: 'CC',
                    uploaderPrincipalName: 'MRC System',
                },
                {
                    id: '3',
                    comment: 'strategy.decision.manual',
                    uploadTimestamp: '2017-12-12T08:11:19Z',
                    uploaderPosition: 'CC',
                    uploaderPrincipalName: 'MRC System',
                },
                {
                    id: '2',
                    comment: 'This is the first comment',
                    uploadTimestamp: '2017-12-12T08:10:19Z',
                    uploaderPosition: 'CM',
                    uploaderPrincipalName: 'alexandru.dita@metrosystems.ro',
                },
            ],
            recommendations: [],
            auditTrail: [
                {
                    id: '60337ac9-a254-4178-8582-70f8f7280cdb',
                    submitInfo: {
                        timestamp: '2020-05-08T13:32:19Z',
                        submitterName: 'Kaschinsky Hugo',
                        submitterPosition: 'CC',
                    },
                    action: 'Review',
                    step: 'Approval',
                    additionalInfo: '{"message":"something"}',
                },
                {
                    id: 'ed621c46-438d-4ec8-945c-7c3e7eeecc39',
                    submitInfo: {
                        timestamp: '2017-12-12T08:20:19Z',
                        submitterName: 'Boehm Andrej',
                        submitterPosition: 'HO',
                    },
                    action: 'Approved',
                    step: 'Approval',
                    additionalInfo: null,
                },
                {
                    id: '3cab9ceb-533a-4390-818a-c63cc72b2cb2',
                    submitInfo: {
                        timestamp: '2017-12-12T08:15:19Z',
                        submitterName: 'Dita Alexandru',
                        submitterPosition: 'CM',
                    },
                    action: 'Approved',
                    step: 'Approval',
                    additionalInfo: null,
                },
                {
                    id: 'b385295d-c63e-4c6e-a2b6-60641d9d05ed',
                    submitInfo: {
                        timestamp: '2017-12-12T08:10:19Z',
                        submitterName: 'Delea Dan-Catalin',
                        submitterPosition: 'CC',
                    },
                    action: 'Requested',
                    step: 'Initialization',
                    additionalInfo: null,
                },
            ],
            requestedItems: [
                {
                    id: '32bfe81f-5782-4c32-a630-459f9eb660fe',
                    customer: {
                        salesLine: 'mcc',
                        country: 'DE',
                        storeNumber: '15',
                        customerNumber: '88194',
                        companyLanguage: null,
                        customerLastName: 'Jensen',
                        customerFirstName: 'Antonio',
                        birthDay: '1973-01-19T23:00:00Z',
                        salutationCode: null,
                        companyFoundationDate: null,
                        companyOwnerLastName: 'Lux companyOwnerLastName',
                        companyOwnerFirstName: 'Anton companyOwnerFirstName',
                        street: 'Huttenberg',
                        houseNumber: '51',
                        zipCode: '88214',
                        city: 'Ravensburg',
                        checkoutCheckCode: null,
                        blockingReason: null,
                        bankAccountNumber: null,
                        bankIdentifier: null,
                        bankName: null,
                        bankRoutingCode: null,
                        bankRoutingSupplement: null,
                        iban: null,
                        accountHolder: null,
                        vatSpecNumber: '1221-1212-1212',
                        vatEuNumber: '1117',
                        legalForm: '7',
                        branchId: null,
                        registrationDate: '2020-05-08T13:32:19Z',
                        commentForCustomer: null,
                        metroClubTypeId: null,
                        mobilePhoneNumber: '212311212',
                        numberOfCards: null,
                        parentStoreNumber: null,
                        parentCustomerNumber: null,
                        phoneNumber: '0751768231',
                        titleName: null,
                        branchFamilyId: null,
                        customerType: null,
                        securityIndicator: null,
                        registrationNumber: null,
                        monitionLevel: null,
                        badDebits: null,
                        debitEntriesNumber: null,
                        attribute1: null,
                        attribute2: null,
                        attribute3: null,
                        attribute4: null,
                        attribute5: null,
                        typeCode: null,
                        creditLimit: 2000,
                        paymentAllowanceCd: null,
                        creditSettleTypeCd: '2',
                        creditSettlePeriodCd: '10',
                        creditSettleFrequencyCd: '2',
                        summaryInvoiceFrequencyCd: null,
                        creditLimitStatus: null,
                        invoiceType: null,
                        limitExhaustion: null,
                        email: 'test@test.com',
                        segment: null,
                        branchDescription: null,
                        legalFormDescription: 'Test',
                        currentPayment: {
                            creditProduct: 'Metro Cash',
                            creditPeriod: '12',
                            debitType: 'Basislaftshiftmandat',
                        },
                    },
                    creditData: [
                        {
                            id: '74359aa1-695e-4a09-bdac-e60adffc192d',
                            amount: 12000,
                            creditProduct: 'Metro Cash',
                            creditPeriod: '12',
                            debitType: 'Basislaftshiftmandat',
                            processedAt: '2017-12-12T08:10:19Z',
                            blockingOption: null,
                        },
                        {
                            id: 'c135ee41-cc00-4da7-962d-7712fb7e0853',
                            amount: 12000,
                            creditProduct: 'Metro Cash',
                            creditPeriod: '12',
                            debitType: 'Basislaftshiftmandat',
                            processedAt: '2017-12-12T08:13:19Z',
                            blockingOption: null,
                        },
                        {
                            id: 'feec8795-0728-4e1d-a674-d43dd4ddac7a',
                            amount: 11000,
                            creditProduct: 'Metro Top',
                            creditPeriod: 'Ende des Monats',
                            debitType: 'Basislaftshiftmandat',
                            processedAt: '2017-12-12T08:15:19Z',
                            blockingOption: null,
                        },
                    ],
                    limitExpiryDate: null,
                    resetToLimitAmount: null,
                },
            ],
            requestedCustomerId: {
                country: 'DE',
                storeNumber: '15',
                customerNumber: '88194',
            },
            requestType: 'LIMIT_REQUEST',
            selectedCreditProgram: null,
            migratedRequest: false,
            lastUpdatedTimestamp: '2020-05-08T13:32:19Z',
            requestStatus: {
                trafficLight: 'yellow',
                creationDate: '2020-05-08T13:32:19Z',
                amount: 11000,
                groupAmount: 0,
                creditProduct: 'Metro Top',
                creditPeriod: 'Ende des Monats',
                debitType: 'Basislaftshiftmandat',
                status: 'Pending',
                position: 'HALJ',
                requestType: 'LIMIT_REQUEST',
                amountBeforeExpiry: null,
                groupMembers: 1,
                applied: true,
            },
            requestedCreditData: {
                id: '74359aa1-695e-4a09-bdac-e60adffc192d',
                amount: 12000,
                creditProduct: 'Metro Cash',
                creditPeriod: '12',
                debitType: 'Basislaftshiftmandat',
                processedAt: '2017-12-12T08:10:19Z',
                blockingOption: null,
            },
        },
    },
    countryCode: 'DE',
    customerInfo: {
        name: '15/88194 Antonio Jensen',
    },
    statusBar: {
        id: '1',
        color: 'yellow',
        limit: 11000,
        text: 'Pending',
        parameters: null,
    },
};

let historyData = {
    countryCode: 'DE',
    countriesWithDifferentBlockingCodes: ['ES'],
    showStrategy: true,
    historyDetails: {
        requestStatus: {
            trafficLight: 'yellow',
            creationDate: '2020-05-08T13:32:19Z',
            amount: 11000,
            groupAmount: 0,
            creditProduct: 'Metro Top',
            creditPeriod: 'Ende des Monats',
            debitType: 'Basislaftshiftmandat',
            status: 'Pending',
            position: 'HALJ',
            requestType: 'LIMIT_REQUEST',
            amountBeforeExpiry: null,
            groupMembers: 1,
            applied: true,
        },
        customerData: {
            accordionDisplayName: '* 15/88194 Antonio Jensen',
            displayName: 'Antonio Jensen',
            customerNumber: '88194',
            storeNumber: '15',
            vatSpecNumber: '1221-1212-1212',
            vatEuNumber: '1117',
            legalForm: '7',
            email: 'test@test.com',
            phoneNumber: '0751768231',
            mobilePhoneNumber: '212311212',
            street: 'Huttenberg',
            houseNumber: '51',
            zipCode: '88214',
            city: 'Ravensburg',
            registrationDate: '2020-05-08T13:32:19Z',
            checkoutCheckCode: null,
            blockingReason: null,
            companyFoundationDate: null,
            branchId: null,
            segment: null,
            branchDescription: null,
            legalFormDescription: 'Test',
            country: 'DE',
            companyAge: '',
            customerLastName: 'Jensen',
            customerFirstName: 'Antonio',
            companyOwnerLastName: 'Lux companyOwnerLastName',
            companyOwnerFirstName: 'Anton companyOwnerFirstName',
            birthDay: '1973-01-19T23:00:00Z',
            limitExhaustion: null,
        },
        requestData: [
            {
                customerData: {
                    accordionDisplayName: '* 15/88194 Antonio Jensen',
                    displayName: 'Antonio Jensen',
                    customerNumber: '88194',
                    storeNumber: '15',
                    vatSpecNumber: '1221-1212-1212',
                    vatEuNumber: '1117',
                    legalForm: '7',
                    email: 'test@test.com',
                    phoneNumber: '0751768231',
                    mobilePhoneNumber: '212311212',
                    street: 'Huttenberg',
                    houseNumber: '51',
                    zipCode: '88214',
                    city: 'Ravensburg',
                    registrationDate: '2020-05-08T13:32:19Z',
                    checkoutCheckCode: null,
                    blockingReason: null,
                    companyFoundationDate: null,
                    branchId: null,
                    segment: null,
                    branchDescription: null,
                    legalFormDescription: 'Test',
                    country: 'DE',
                    companyAge: '',
                    customerLastName: 'Jensen',
                    customerFirstName: 'Antonio',
                    companyOwnerLastName: 'Lux companyOwnerLastName',
                    companyOwnerFirstName: 'Anton companyOwnerFirstName',
                    birthDay: '1973-01-19T23:00:00Z',
                    limitExhaustion: null,
                },
                current: {
                    creditLimit: 2000,
                    creditPeriod: '12',
                    creditProduct: 'Metro Cash',
                    debitType: 'Basislaftshiftmandat',
                    blockingOption: null,
                },
                requested: {
                    creditLimit: 12000,
                    creditPeriod: '12',
                    creditProduct: 'Metro Cash',
                    debitType: 'Basislaftshiftmandat',
                    blockingOption: null,
                },
                applied: {
                    creditLimit: 11000,
                    creditPeriod: 'Ende des Monats',
                    creditProduct: 'Metro Top',
                    debitType: 'Basislaftshiftmandat',
                    blockingOption: null,
                },
                limitExpiryDate: null,
                resetToLimitAmount: null,
            },
        ],
        salesOverviews: [
            {
                customerId: {
                    salesLine: 'mcc',
                    country: 'DE',
                    storeNumber: '15',
                    customerNumber: '88194',
                },
                displayName: '* 15/88194 Antonio Jensen',
                purchasesQuintet: {
                    l1m: 1,
                    l3m: 1,
                    l6m: 1,
                    l12m: 1,
                },
                invoicesQuintet: {
                    l1m: 1,
                    l3m: 1,
                    l6m: 1,
                    l12m: 1,
                },
                totalQuintet: {
                    l1m: 1,
                    l3m: 1,
                    l6m: 1,
                    l12m: 1,
                },
                totalGrossProfitQuintet: {
                    l1m: 0,
                    l3m: 0,
                    l6m: 0,
                    l12m: 0,
                },
                totalMarginQuintet: {
                    l1m: 0,
                    l3m: 0,
                    l6m: 0,
                    l12m: 0,
                },
                behaviorQuintets: [
                    {
                        behaviouralCode: 1,
                        quintetValues: {
                            l1m: 1,
                            l3m: 1,
                            l6m: 1,
                            l12m: 1,
                        },
                    },
                    {
                        behaviouralCode: 2,
                        quintetValues: {
                            l1m: 1,
                            l3m: 1,
                            l6m: 1,
                            l12m: 1,
                        },
                    },
                ],
            },
        ],
        paymentsOverviews: {
            deactivated: false,
            allCompleted: false,
            sapDataForCustomers: [
                {
                    displayName: '* 15/88194 Antonio Jensen',
                    customerSapDataList: [
                        {
                            countryId: 'DE',
                            storeIdCustomer: '15',
                            customerId: '88194',
                            sapCustomerNo: '88194',
                            documentDate: '2020-06-17T09:11:40Z',
                            amountLocalCurrency: 10000,
                            currency: 'EUR',
                            arrears: 1,
                            dunningLevel: '0',
                            dunningBlock: '',
                            dueDateInvoice: '2020-06-17T09:11:40Z',
                            specialDCIndicator: 'H',
                            customerIdEntity: {
                                salesLine: 'mcc',
                                country: 'DE',
                                storeNumber: '15',
                                customerNumber: '88194',
                            },
                        },
                    ],
                },
            ],
        },
        comments: [
            {
                id: '1',
                comment: 'This is the second comment',
                uploadTimestamp: '2020-05-08T13:32:19Z',
                uploaderPosition: 'CC',
                uploaderPrincipalName: 'MRC System',
            },
            {
                id: '3',
                comment: 'strategy.decision.manual',
                uploadTimestamp: '2017-12-12T08:11:19Z',
                uploaderPosition: 'CC',
                uploaderPrincipalName: 'MRC System',
            },
            {
                id: '2',
                comment: 'This is the first comment',
                uploadTimestamp: '2017-12-12T08:10:19Z',
                uploaderPosition: 'CM',
                uploaderPrincipalName: 'alexandru.dita@metrosystems.ro',
            },
        ],
        recommendations: [],
        attachments: [
            {
                title: 'This is a csv file',
                type: 'csv',
                fileType: 'fileType',
                uri: 'http://google.ro',
                expiryDate: null,
                amount: null,
                metadataJson: null,
                uploadTimestamp: '2017-12-12T08:10:19Z',
                uploaderPosition: 'HO',
                uploaderPrincipalName: 'dan-catalin.delea@metrosystems.ro',
                markedForDeletion: false,
                contentType: 'text/csv',
            },
            {
                title: 'This is a pdf file',
                type: 'pdf',
                fileType: 'contract',
                uri: 'http://google.ro',
                expiryDate: '2020-05-18T13:32:19Z',
                amount: 100,
                metadataJson:
                    '{"country":"DE","type":"contract","label":"mrc.attachments.types.contract","remark":"Digital version to improve efficiency","fields":[{"field_label":"mrc.attachments.fields.contract.start_date","data_type":"Date","mandatory":true,"validation_operation":"LESS_THAN_AND_EQUALS","validation_argument":"TODAY","value":1580940000000},{"field_label":"mrc.attachments.fields.contract.expiration_date","data_type":"Date","mandatory":true,"field_in_db":"expiry_date","validation_operation":"GREATER_THAN_AND_EQUALS","validation_argument":"TODAY","value":1581026400000}]}',
                uploadTimestamp: '2020-05-08T13:32:19Z',
                uploaderPosition: 'CC',
                uploaderPrincipalName: 'alexandru.dita@metrosystems.ro',
                markedForDeletion: false,
                contentType: 'application/pdf',
            },
        ],
        auditTrailDetails: {
            phaseSet: [
                {
                    auditStep: 'Approval',
                    items: [
                        {
                            date: null,
                            user: '- (CC)',
                            status: 'Pending',
                            additionalInfo: null,
                        },
                        {
                            date: null,
                            user: '- (HOT)',
                            status: 'Pending',
                            additionalInfo: null,
                        },
                        {
                            date: null,
                            user: '- (HALJ)',
                            status: 'Pending',
                            additionalInfo: null,
                        },
                        {
                            date: '2020-05-08T13:32:19Z',
                            user: 'Kaschinsky Hugo (CC)',
                            status: 'Review',
                            additionalInfo: {
                                retriesLeft: null,
                                requestId: null,
                                responses: null,
                                activationStatus: null,
                                isRetriable: false,
                            },
                        },
                        {
                            date: '2017-12-12T08:20:19Z',
                            user: 'Boehm Andrej (HO)',
                            status: 'Approved',
                            additionalInfo: null,
                        },
                        {
                            date: '2017-12-12T08:15:19Z',
                            user: 'Dita Alexandru (CM)',
                            status: 'Approved',
                            additionalInfo: null,
                        },
                    ],
                    overviewStatus: 'Pending',
                },
                {
                    auditStep: 'Initialization',
                    items: [
                        {
                            date: '2017-12-12T08:10:19Z',
                            user: 'Delea Dan-Catalin (CC)',
                            status: 'Requested',
                            additionalInfo: null,
                        },
                    ],
                    overviewStatus: 'Requested',
                },
            ],
        },
        strategyKeyIndicatorsData: {
            requestedGroupLimit: 8500,
            groupInfo: [
                {
                    country: 'DE',
                    storeNumber: '13',
                    customerNumber: '6975',
                    badDebits: 0,
                },
                {
                    country: 'DE',
                    storeNumber: '13',
                    customerNumber: '57485',
                    badDebits: 0,
                },
                {
                    country: 'DE',
                    storeNumber: '13',
                    customerNumber: '97247',
                    badDebits: 0,
                },
            ],
            customerprovider: [
                {
                    countryId: 'DE',
                    saleslineId: 'MCC',
                    storeIdCustomer: '13',
                    customerId: '57485',
                    customerTypeCd: 'NORM',
                    clearingDate: null,
                    fiscalYear: '2018',
                    postingDate: '2018-09-14T00:00:00Z',
                    documentDate: '2018-09-14T00:00:00Z',
                    currency: 'EUR',
                    periodFiscalYear: '12',
                    specialDCIndicator: 'S',
                    amountLocalCurrency: 57.84,
                    amountDocumentCurrency: 57.84,
                    baselinePaymentDate: '2018-09-28T00:00:00Z',
                    dunningBlock: '',
                    dunningKey: '',
                    lastDunningDate: null,
                    dunningLevel: '0',
                    indicatorClearingReversed: '',
                    sapCustomerNo: '1013057485',
                    sapDocumentNo: '6203493325',
                    sapLineItemNo: '001',
                    customerName: 'TSV Bayer 04 Leverkusen e.V.',
                    referenceDocNo: '0003051039',
                    dirctDebitBounced: null,
                    salesTaxIndicator: '',
                    dueDateInvoice: '2018-09-28T00:00:00Z',
                    flagReversedDocument: '0',
                    assignment: '20180914',
                    documentType: 'CI',
                    text: '* 013-057485 R:0003-051039 H:013',
                    paymentDate: null,
                    arrears: 112,
                },
            ],
            scoringservice: {
                internalScore: null,
            },
            keyIndicators: {
                requestedAt: '2019-01-18T12:23:28.481Z',
                indicators: {
                    'strategy.keyindicators.dunninglevel': [0, 'OK'],
                    'strategy.keyindicators.badDebits': ['-', 'NOT_OK'],
                    'strategy.keyindicators.paymentTermsPeriod': ['mrc.payment.Mitte_und_Ende_des_Monats', 'SEMI_OK'],
                },
                missingIndicators: ['strategy.keyindicators.internalScore'],
            },
        },
        scores: [
            {
                scoreId: null,
                score: '100',
                evaluation: 'POSITIVE',
                customerId: '15/88194',
                agency: 'MRC',
                limit: null,
                uploadedBy: null,
                requestedAt: '2020-05-08T13:32:19Z',
                errorCode: null,
                reportPath: null,
            },
            {
                scoreId: null,
                score: '200',
                evaluation: 'POSITIVE',
                customerId: '15/88194',
                agency: 'SCHUFA_B2B',
                limit: '10000',
                uploadedBy: 'test.user@metronom.com',
                requestedAt: '2020-05-08T13:32:19Z',
                errorCode: null,
                reportPath: '/history/mocks/extscore/report/12321',
            },
            {
                scoreId: null,
                score: '1',
                evaluation: 'POSITIVE',
                customerId: '15/88194',
                agency: 'MCC_SCORE',
                limit: null,
                uploadedBy: 'test.user@metronom.com',
                requestedAt: '2020-05-08T13:32:19Z',
                errorCode: null,
                reportPath: null,
            },
        ],
        historicExtScores: [
            {
                scoreId: '1111',
                score: '333',
                evaluation: null,
                customerId: '123',
                agency: 'SCHUFA_B2B',
                limit: null,
                uploadedBy: 'MRC',
                requestedAt: '2020-05-08T13:32:19Z',
                errorCode: null,
                reportPath: null,
            },
        ],
        approvalProcess: {
            id: '-111111111111',
            request: {
                id: '-1234',
                creationTimestamp: '2020-05-08T13:32:19Z',
                attachments: [
                    {
                        id: 'ebbc89ad-c59d-4860-a9b4-bc0d5802f43a',
                        contentUri: 'http://google.ro',
                        title: 'This is a csv file',
                        size: 1233,
                        contentType: 'text/csv',
                        filename: 'filename_csv.csv',
                        fileType: 'fileType',
                        uploadTimestamp: '2017-12-12T08:10:19Z',
                        uploaderPosition: 'HO',
                        uploaderPrincipalName: 'dan-catalin.delea@metrosystems.ro',
                        expiryDate: null,
                        amount: null,
                        metadataJson: null,
                        markedForDeletion: false,
                    },
                    {
                        id: '6d6d26b3-3346-4da3-8440-b98d728c513f',
                        contentUri: 'http://google.ro',
                        title: 'This is a pdf file',
                        size: 1233,
                        contentType: 'application/pdf',
                        filename: 'filename_pdf.pdf',
                        fileType: 'contract',
                        uploadTimestamp: '2020-05-08T13:32:19Z',
                        uploaderPosition: 'CC',
                        uploaderPrincipalName: 'alexandru.dita@metrosystems.ro',
                        expiryDate: '2020-05-18T13:32:19Z',
                        amount: 100,
                        metadataJson:
                            '{"country":"DE","type":"contract","label":"mrc.attachments.types.contract","remark":"Digital version to improve efficiency","fields":[{"field_label":"mrc.attachments.fields.contract.start_date","data_type":"Date","mandatory":true,"validation_operation":"LESS_THAN_AND_EQUALS","validation_argument":"TODAY","value":1580940000000},{"field_label":"mrc.attachments.fields.contract.expiration_date","data_type":"Date","mandatory":true,"field_in_db":"expiry_date","validation_operation":"GREATER_THAN_AND_EQUALS","validation_argument":"TODAY","value":1581026400000}]}',
                        markedForDeletion: false,
                    },
                ],
                comments: [
                    {
                        id: '1',
                        comment: 'This is the second comment',
                        uploadTimestamp: '2020-05-08T13:32:19Z',
                        uploaderPosition: 'CC',
                        uploaderPrincipalName: 'MRC System',
                    },
                    {
                        id: '3',
                        comment: 'strategy.decision.manual',
                        uploadTimestamp: '2017-12-12T08:11:19Z',
                        uploaderPosition: 'CC',
                        uploaderPrincipalName: 'MRC System',
                    },
                    {
                        id: '2',
                        comment: 'This is the first comment',
                        uploadTimestamp: '2017-12-12T08:10:19Z',
                        uploaderPosition: 'CM',
                        uploaderPrincipalName: 'alexandru.dita@metrosystems.ro',
                    },
                ],
                recommendations: [],
                auditTrail: [
                    {
                        id: '60337ac9-a254-4178-8582-70f8f7280cdb',
                        submitInfo: {
                            timestamp: '2020-05-08T13:32:19Z',
                            submitterName: 'Kaschinsky Hugo',
                            submitterPosition: 'CC',
                        },
                        action: 'Review',
                        step: 'Approval',
                        additionalInfo: '{"message":"something"}',
                    },
                    {
                        id: 'ed621c46-438d-4ec8-945c-7c3e7eeecc39',
                        submitInfo: {
                            timestamp: '2017-12-12T08:20:19Z',
                            submitterName: 'Boehm Andrej',
                            submitterPosition: 'HO',
                        },
                        action: 'Approved',
                        step: 'Approval',
                        additionalInfo: null,
                    },
                    {
                        id: '3cab9ceb-533a-4390-818a-c63cc72b2cb2',
                        submitInfo: {
                            timestamp: '2017-12-12T08:15:19Z',
                            submitterName: 'Dita Alexandru',
                            submitterPosition: 'CM',
                        },
                        action: 'Approved',
                        step: 'Approval',
                        additionalInfo: null,
                    },
                    {
                        id: 'b385295d-c63e-4c6e-a2b6-60641d9d05ed',
                        submitInfo: {
                            timestamp: '2017-12-12T08:10:19Z',
                            submitterName: 'Delea Dan-Catalin',
                            submitterPosition: 'CC',
                        },
                        action: 'Requested',
                        step: 'Initialization',
                        additionalInfo: null,
                    },
                ],
                requestedItems: [
                    {
                        id: '32bfe81f-5782-4c32-a630-459f9eb660fe',
                        customer: {
                            salesLine: 'mcc',
                            country: 'DE',
                            storeNumber: '15',
                            customerNumber: '88194',
                            companyLanguage: null,
                            customerLastName: 'Jensen',
                            customerFirstName: 'Antonio',
                            birthDay: '1973-01-19T23:00:00Z',
                            salutationCode: null,
                            companyFoundationDate: null,
                            companyOwnerLastName: 'Lux companyOwnerLastName',
                            companyOwnerFirstName: 'Anton companyOwnerFirstName',
                            street: 'Huttenberg',
                            houseNumber: '51',
                            zipCode: '88214',
                            city: 'Ravensburg',
                            checkoutCheckCode: null,
                            blockingReason: null,
                            bankAccountNumber: null,
                            bankIdentifier: null,
                            bankName: null,
                            bankRoutingCode: null,
                            bankRoutingSupplement: null,
                            iban: null,
                            accountHolder: null,
                            vatSpecNumber: '1221-1212-1212',
                            vatEuNumber: '1117',
                            legalForm: '7',
                            branchId: null,
                            registrationDate: '2020-05-08T13:32:19Z',
                            commentForCustomer: null,
                            metroClubTypeId: null,
                            mobilePhoneNumber: '212311212',
                            numberOfCards: null,
                            parentStoreNumber: null,
                            parentCustomerNumber: null,
                            phoneNumber: '0751768231',
                            titleName: null,
                            branchFamilyId: null,
                            customerType: null,
                            securityIndicator: null,
                            registrationNumber: null,
                            monitionLevel: null,
                            badDebits: null,
                            debitEntriesNumber: null,
                            attribute1: null,
                            attribute2: null,
                            attribute3: null,
                            attribute4: null,
                            attribute5: null,
                            typeCode: null,
                            creditLimit: 2000,
                            paymentAllowanceCd: null,
                            creditSettleTypeCd: '2',
                            creditSettlePeriodCd: '10',
                            creditSettleFrequencyCd: '2',
                            summaryInvoiceFrequencyCd: null,
                            creditLimitStatus: null,
                            invoiceType: null,
                            limitExhaustion: null,
                            email: 'test@test.com',
                            segment: null,
                            branchDescription: null,
                            legalFormDescription: 'Test',
                            currentPayment: {
                                creditProduct: 'Metro Cash',
                                creditPeriod: '12',
                                debitType: 'Basislaftshiftmandat',
                            },
                        },
                        creditData: [
                            {
                                id: '74359aa1-695e-4a09-bdac-e60adffc192d',
                                amount: 12000,
                                creditProduct: 'Metro Cash',
                                creditPeriod: '12',
                                debitType: 'Basislaftshiftmandat',
                                processedAt: '2017-12-12T08:10:19Z',
                                blockingOption: null,
                            },
                            {
                                id: 'c135ee41-cc00-4da7-962d-7712fb7e0853',
                                amount: 12000,
                                creditProduct: 'Metro Cash',
                                creditPeriod: '12',
                                debitType: 'Basislaftshiftmandat',
                                processedAt: '2017-12-12T08:13:19Z',
                                blockingOption: null,
                            },
                            {
                                id: 'feec8795-0728-4e1d-a674-d43dd4ddac7a',
                                amount: 11000,
                                creditProduct: 'Metro Top',
                                creditPeriod: 'Ende des Monats',
                                debitType: 'Basislaftshiftmandat',
                                processedAt: '2017-12-12T08:15:19Z',
                                blockingOption: null,
                            },
                        ],
                        limitExpiryDate: null,
                        resetToLimitAmount: null,
                    },
                ],
                requestedCustomerId: {
                    country: 'DE',
                    storeNumber: '15',
                    customerNumber: '88194',
                },
                requestType: 'LIMIT_REQUEST',
                selectedCreditProgram: null,
                migratedRequest: false,
                lastUpdatedTimestamp: '2020-05-08T13:32:19Z',
                requestStatus: null,
                requestedCreditData: {
                    id: '74359aa1-695e-4a09-bdac-e60adffc192d',
                    amount: 12000,
                    creditProduct: 'Metro Cash',
                    creditPeriod: '12',
                    debitType: 'Basislaftshiftmandat',
                    processedAt: '2017-12-12T08:10:19Z',
                    blockingOption: null,
                },
            },
            approvalFlowJson:
                '{"country":"DE","requested":{"amount":2000.0,"creditProduct":"METRO Cash","debitType":"Firmenlastschriftmandat","creditPeriod":"10"},"current":{"amount":1000.0,"creditProduct":"METRO Cash","debitType":"Firmenlastschriftmandat","creditPeriod":"10"},"version":"1","steps":[{"id":"CMAPPROVE","position":"CM","type":"APPROVE"},{"id":"HALJAPPROVE","position":"HALJ","type":"APPROVE"},{"id":"HOTAPPROVE","position":"HOT","type":"APPROVE"},{"id":"CCCONTRACTING","position":"CC","type":"CONTRACTING_LIGHT"}]}',
            keyIndicatorsJson:
                '{"requestedGroupLimit":8500,"groupInfo":[{"country":"DE","storeNumber":"13","customerNumber":"6975","badDebits":0},{"country":"DE","storeNumber":"13","customerNumber":"57485","badDebits":0},{"country":"DE","storeNumber":"13","customerNumber":"97247","badDebits":0}],"customerprovider":[{"countryId":"DE","saleslineId":"MCC","storeIdCustomer":"13","customerId":"57485","customerTypeCd":"NORM","clearingDate":null,"fiscalYear":"2018","postingDate":"2018-09-14T00:00:00Z","documentDate":"2018-09-14T00:00:00Z","currency":"EUR","periodFiscalYear":"12","specialDCIndicator":"S","amountLocalCurrency":57.84,"amountDocumentCurrency":57.84,"baselinePaymentDate":"2018-09-28T00:00:00Z","dunningBlock":"","dunningKey":"","lastDunningDate":null,"dunningLevel":"0","indicatorClearingReversed":"","sapCustomerNo":"1013057485","sapDocumentNo":"6203493325","sapLineItemNo":"001","customerName":"TSV Bayer 04 Leverkusen e.V.","referenceDocNo":"0003051039","dirctDebitBounced":null,"salesTaxIndicator":"","dueDateInvoice":"2018-09-28T00:00:00Z","flagReversedDocument":"0","assignment":"20180914","documentType":"CI","text":"* 013-057485 R:0003-051039 H:013","paymentDate":null,"arrears":112}],"scoringservice":{"internalScore":null},"keyIndicators":{"requestedAt":"2019-01-18T12:23:28.481Z","indicators":{"strategy.keyindicators.dunninglevel":[0,"OK"],"strategy.keyindicators.badDebits":["-","NOT_OK"],"strategy.keyindicators.paymentTermsPeriod":["mrc.payment.Mitte_und_Ende_des_Monats","SEMI_OK"]},"missingIndicators":["strategy.keyindicators.internalScore"]}}',
            automaticDecisionAt: '2020-05-08T13:32:19Z',
            decisiveIndicators: '[strategy.keyindicators.badDebits]',
            strategyDecision: 'Manual',
        },
        currentGroupLimit: 2000,
        limitExhaustionGroupLimit: null,
        requestedGroupLimit: 12000,
        appliedGroupLimit: 11000,
        selectedCreditProgram: null,
        validMccScore: {
            scoreId: null,
            score: '1',
            evaluation: 'POSITIVE',
            customerId: '15/88194',
            agency: 'MCC_SCORE',
            limit: null,
            uploadedBy: 'test.user@metronom.com',
            requestedAt: '2020-05-08T13:32:19Z',
            errorCode: null,
            reportPath: null,
        },
    },
    statusBar: null,
};

let additionalFields = {
    requestFields: [
        {
            id: 'c575e25f-0549-40d4-a11c-a6b8175cccb9',
            requestId: '1',
            country: 'DE',
            storeNumber: '19',
            customerNumber: '77123',
            groupId: null,
            creationTimestamp: '2020-06-17T08:18:49.210748Z',
            value: 'Computer_peripheral_equipment|Recreational_Products_Toys',
            textValue: null,
            countryField: {
                id: 'e3992ab5-425c-45ed-99f6-c82f63ea9be0',
                mandatory: false,
                validation: null,
                level: 'CUSTOMER',
                order: 5,
                section: 'CREDIT_DATA',
                reusable: true,
                endTimestamp: null,
                country: 'DE',
                options:
                    'Oil_Gas_Production|Computer_peripheral_equipment|Recreational_Products_Toys|Electric_Utilities_Central|Package_Goods_Cosmetics|EDP_Services|Commercial_Banks|Metal_Fabrications|Industrial_Machinery_Components',
                field: {
                    id: '2bcc9833-1aa8-40ed-8b31-985a28fa906e',
                    code: 'DMY_CUSTOMER_INDUSTRY',
                    label: 'mrc.customerdetails.industry',
                    type: 'DROPDOWN_MULTIPLE',
                },
            },
        },
        {
            id: '5e2deb9a-6f42-4459-8894-9d4a4e767ccf',
            requestId: '1',
            country: 'DE',
            storeNumber: '19',
            customerNumber: '77123',
            groupId: null,
            creationTimestamp: '2020-06-17T08:18:49.210818Z',
            value: 'true',
            textValue: null,
            countryField: {
                id: 'cb45aef4-bbe7-4f1d-95d2-ece99a148a1d',
                mandatory: false,
                validation: null,
                level: 'CUSTOMER',
                order: 6,
                section: 'CREDIT_DATA',
                reusable: true,
                endTimestamp: null,
                country: 'DE',
                options: null,
                field: {
                    id: 'a6c4d42a-43db-400b-a515-077a327be619',
                    code: 'DMY_CUSTOMER_IS_PROFITABLE',
                    label: 'mrc.customer.is.profitable',
                    type: 'CHECKBOX',
                },
            },
        },
        {
            id: '3774ce0f-2d6c-4a60-9e68-35acc9f7021d',
            requestId: '1',
            country: 'DE',
            storeNumber: '19',
            customerNumber: '77123',
            groupId: null,
            creationTimestamp: '2020-06-17T08:18:49.210070Z',
            value: '123',
            textValue: null,
            countryField: {
                id: '0660f875-b508-4f66-9cc7-141f1e1a962b',
                mandatory: true,
                validation: 'isNumber',
                level: 'GROUP',
                order: 1,
                section: 'CREDIT_DATA',
                reusable: true,
                endTimestamp: null,
                country: 'DE',
                options: null,
                field: {
                    id: 'c2a83b05-e05e-40e7-bfa9-8fd5835e4b94',
                    code: 'DMY_GROUP_TOTAL_TURNOVER',
                    label: 'mrc.mdw.totalturnover',
                    type: 'NUMBER',
                },
            },
        },
        {
            id: 'af757682-a57f-4cfc-988f-e7613becced7',
            requestId: '1',
            country: 'DE',
            storeNumber: '19',
            customerNumber: '77123',
            groupId: null,
            creationTimestamp: '2020-06-17T08:18:49.210683Z',
            value: '2020-12-31',
            textValue: null,
            countryField: {
                id: 'f017993c-9338-45c4-abfb-6c61f407f4c3',
                mandatory: false,
                validation: 'isDateInFuture',
                level: 'CUSTOMER',
                order: 4,
                section: 'CREDIT_DATA',
                reusable: true,
                endTimestamp: null,
                country: 'DE',
                options: null,
                field: {
                    id: 'f47f3f98-a953-4c2b-b4a0-b050fbd0da92',
                    code: 'DMY_CUSTOMER_CONTRACT_EXPIRATION_DATE',
                    label: 'mrc.attachments.fields.contract.expiration_date',
                    type: 'DATE',
                },
            },
        },
        {
            id: 'c7e21ba8-b905-4b50-92b4-3faee334f129',
            requestId: '1',
            country: 'DE',
            storeNumber: '19',
            customerNumber: '77123',
            groupId: null,
            creationTimestamp: '2020-06-17T08:18:49.210475Z',
            value: null,
            textValue:
                "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
            countryField: {
                id: 'c4ff9118-2886-4461-9037-59a530794a56',
                mandatory: false,
                validation: 'maxLength255',
                level: 'REQUEST',
                order: 2,
                section: 'CREDIT_DATA',
                reusable: false,
                endTimestamp: null,
                country: 'DE',
                options: null,
                field: {
                    id: '3e112e86-4c0b-4c0f-b014-4a586b067dd7',
                    code: 'DMY_REQUEST_COMMENT',
                    label: 'mrc.request.comment',
                    type: 'TEXTAREA',
                },
            },
        },
        {
            id: 'e4e10af6-07c0-4cd5-a600-051c3677134a',
            requestId: '1',
            country: 'DE',
            storeNumber: '19',
            customerNumber: '77123',
            groupId: null,
            creationTimestamp: '2020-06-17T08:18:49.210524Z',
            value: 'example of string value',
            textValue: null,
            countryField: {
                id: '5f36fbc7-c1c7-44df-a8df-fc0ea90c42b7',
                mandatory: false,
                validation: 'maxLength255',
                level: 'CUSTOMER',
                order: 1,
                section: 'CREDIT_DATA',
                reusable: true,
                endTimestamp: null,
                country: 'DE',
                options: null,
                field: {
                    id: 'eef491e5-466d-4f97-bf17-ea68208d1a73',
                    code: 'DMY_CUSTOMER_COMPANY_NAME',
                    label: 'mrc.customerdetails.fields.companyname',
                    type: 'TEXT',
                },
            },
        },
        {
            id: '10983f71-9ed7-477c-afd8-7305ae51380e',
            requestId: '1',
            country: 'DE',
            storeNumber: '19',
            customerNumber: '77123',
            groupId: null,
            creationTimestamp: '2020-06-17T08:18:49.210586Z',
            value: 'sample@example.com',
            textValue: null,
            countryField: {
                id: '9789dade-f6e7-4e72-ae24-7f219d80d40f',
                mandatory: true,
                validation: 'isEmail',
                level: 'CUSTOMER',
                order: 2,
                section: 'CREDIT_DATA',
                reusable: true,
                endTimestamp: null,
                country: 'DE',
                options: null,
                field: {
                    id: '12de83a4-1b56-482b-b283-a1209ca9e71e',
                    code: 'DMY_CUSTOMER_EMAIL',
                    label: 'mrc.customerdetails.fields.email',
                    type: 'TEXT',
                },
            },
        },
        {
            id: '506d0917-bfc5-44b7-ba40-31f31db2e329',
            requestId: '1',
            country: 'DE',
            storeNumber: '19',
            customerNumber: '77123',
            groupId: null,
            creationTimestamp: '2020-06-17T08:18:49.210644Z',
            value: '+49 30 901820',
            textValue: null,
            countryField: {
                id: '1e6519b8-f7d5-4698-8b62-bbaba20820ba',
                mandatory: true,
                validation: 'isPhone',
                level: 'CUSTOMER',
                order: 3,
                section: 'CREDIT_DATA',
                reusable: true,
                endTimestamp: null,
                country: 'DE',
                options: null,
                field: {
                    id: 'b43c8585-2a4f-4055-a2b5-3b174d3a30f4',
                    code: 'DMY_CUSTOMER_PHONE',
                    label: 'mrc.customerdetails.fields.phone',
                    type: 'TEXT',
                },
            },
        },
        {
            id: '6fd5ca6c-f33f-49bc-ae37-652d54a018b1',
            requestId: '1',
            country: 'DE',
            storeNumber: '19',
            customerNumber: '77123',
            groupId: null,
            creationTimestamp: '2020-06-17T08:18:49.210173Z',
            value: '75',
            textValue: null,
            countryField: {
                id: '0490c4a8-d46c-4ca4-968c-e0924e4eca74',
                mandatory: true,
                validation: 'isPercentage',
                level: 'GROUP',
                order: 2,
                section: 'CREDIT_DATA',
                reusable: true,
                endTimestamp: null,
                country: 'DE',
                options: null,
                field: {
                    id: '9ec81e6b-9e61-4663-8069-cd62c701fe05',
                    code: 'DMY_GROUP_PROFITABILITY',
                    label: 'mrc.topmanagement.profitability',
                    type: 'NUMBER',
                },
            },
        },
        {
            id: '38b8679f-f653-4e30-888d-809c8e293b19',
            requestId: '1',
            country: 'DE',
            storeNumber: '19',
            customerNumber: '77123',
            groupId: null,
            creationTimestamp: '2020-06-17T08:18:49.210286Z',
            value: '20',
            textValue: null,
            countryField: {
                id: '2e6cb78c-e5a9-49cc-93db-6a3e4db10990',
                mandatory: false,
                validation: 'isNumber',
                level: 'GROUP',
                order: 3,
                section: 'CREDIT_DATA',
                reusable: false,
                endTimestamp: null,
                country: 'DE',
                options: null,
                field: {
                    id: 'bbc8c7e4-b9d6-46b4-844b-9eca65829773',
                    code: 'DMY_GROUP_LIMIT_AVERAGE',
                    label: 'mrc.limit.average',
                    type: 'NUMBER',
                },
            },
        },
        {
            id: 'f2ef62fc-c85c-4f31-b414-32617e215420',
            requestId: '1',
            country: 'DE',
            storeNumber: '19',
            customerNumber: '77123',
            groupId: null,
            creationTimestamp: '2020-06-17T08:18:49.210378Z',
            value: '3',
            textValue: null,
            countryField: {
                id: 'ede80e37-7718-46b0-8566-eddcef681161',
                mandatory: false,
                validation: null,
                level: 'GROUP',
                order: 4,
                section: 'CREDIT_DATA',
                reusable: true,
                endTimestamp: null,
                country: 'DE',
                options: '1|2|3|4|5',
                field: {
                    id: 'a0ca6a5a-2783-448f-a9c7-aefcd5b23f75',
                    code: 'DMY_GROUP_GENERAL_RATING',
                    label: 'mrc.recommendations.rating',
                    type: 'RADIOBUTTON',
                },
            },
        },
        {
            id: '038beda3-6bf6-4183-891c-b5080d936456',
            requestId: '1',
            country: 'DE',
            storeNumber: '19',
            customerNumber: '77123',
            groupId: null,
            creationTimestamp: '2020-06-17T08:18:49.210420Z',
            value: 'VERY_IMPORTANT',
            textValue: null,
            countryField: {
                id: '4cc61cef-80eb-44ab-850b-a7899e566629',
                mandatory: true,
                validation: null,
                level: 'REQUEST',
                order: 1,
                section: 'CREDIT_DATA',
                reusable: false,
                endTimestamp: null,
                country: 'DE',
                options: 'NOT_IMPORTANT|IMPORTANT|VERY_IMPORTANT',
                field: {
                    id: 'a09bd711-d0f1-4900-8672-37acf6b983e8',
                    code: 'DMY_REQUEST_IMPORTANCE',
                    label: 'mrc.request.importance',
                    type: 'DROPDOWN',
                },
            },
        },
    ],
};

storiesOf('History/CustomerSummary', module)
    .add('with history', () => <CustomerSummary {...historyCustomerData} noHistory={false} />)
    .add('no history', () => <CustomerSummary {...historyCustomerData} noHistory={true} />);

storiesOf('History/HistoryDetails', module).add('history details', () => (
    <HistoryDetails
        error={false}
        isTablet={true}
        buttonsDisabled={false}
        // {...historyData}

        // notificationShowing: PropTypes.string // bool?
        requestData={historyData.historyDetails.requestData}
        approvalProcess={historyData.historyDetails.approvalProcess}
        groupLimit={historyData.historyDetails.groupLimit}
        salesOverviews={historyData.historyDetails.salesOverviews}
        paymentsOverviews={historyData.historyDetails.paymentsOverviews}
        scores={historyData.historyDetails.scores}
        historicExtScores={historyData.historyDetails.historicExtScores}
        strategyKeyIndicatorsData={historyData.historyDetails.strategyKeyIndicatorsData}
        comments={historyData.historyDetails.comments}
        attachments={historyData.historyDetails.attachments}
        auditTrailDetails={historyData.historyDetails.auditTrailDetails}
        requestStatus={historyData.historyDetails.requestStatus}
        validMccScore={historyData.historyDetails.validMccScore}
        statusBar={historyData.statusBar}
        countryCode={historyData.countryCode}
        retry={value => console.log(value)}
        cancelActivation={value => console.log(value)}
        cancelApproval={value => console.log(value)}
        recommendations={historyData.historyDetails.recommendations}
        additionalFields={additionalFields}
        countriesWithDifferentBlockingCodes={historyData.countriesWithDifferentBlockingCodes}

        // history: PropTypes.object // not used!?
    />
));
